name: Feature request
description: Suggest a feature for c15t
labels: ["feature"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What are you trying to do that's hard or impossible today?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Mockups, prior art, use cases.
    validations:
      required: false
