name: GitHub Actions Security

on:
  pull_request:
    paths:
      - '.github/workflows/**'
      - '.github/actions/**'
  push:
    branches: ['main']
    paths:
      - '.github/workflows/**'
      - '.github/actions/**'
  workflow_dispatch:

permissions: {}

jobs:
  zizmor:
    name: zizmor
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
    steps:
      - name: Check out repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@e639db99335bc9038abc0e066dfcd72e23d26fb4 # v0.3.0
        with:
          advanced-security: false
          annotations: true
          persona: auditor
          min-severity: high
          min-confidence: medium
